

data:
  data_module: DataModule_CRL
  eval_module: EvalModule
  preference_data_path: ../datasets/train/preference_dataset_seperate.json
  VLfeedback_data_path: ../datasets/train/VLfeedback_dataset_seperate.json
  eval_data_path: ../datasets/eval/evaluation_data.jsonl
  ratio: 1
model:
  model_module: llava

training:
  epochs: 1
  accumulate_grad_batches: 64
  weight_decay: 0.01
  learning_rate: 0.0001 # 0.002
  # checkpoint_every_n_steps: 

output_dir: ../model_output/output_model_CRL
eval_output_path: ../eval_results/CRL_eval_results.jsonl