

data:
  data_module: DataModule_Multiturn
  eval_module: EvalModule
  preference_data_path: ../datasets/train/preference_dataset_multiturn.json
  VLfeedback_data_path: ../datasets/train/vlfeedback_nlf_conversations.jsonl
  eval_data_path: ../datasets/eval/evaluation_data.jsonl

  
model:
  model_module: llava

training:
  epochs: 1
  accumulate_grad_batches: 32
  weight_decay: 0.01
  learning_rate: 0.0001 # 0.002
  # checkpoint_every_n_steps: 

output_dir: ../model_output/output_model_multiturn
eval_output_path: ../eval_results/multiturn_eval_results.jsonl